name: dapp1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  material_segmented_control: ^5.0.0  
  #youtube_player_flutter: ^9.0.1
  
    


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true
  assets:
    
    - assets/book.png
    - assets/uniquslogo.png